name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - name: "Build container"
        id: build-container
        run: |
          docker build -t my-container:my-tag .
      - name: "List containers"
        id: list-containers
        run: |
          docker images
      - name: Scan for LOW, MED vulnerabilities
        uses: docker://docker.io/aquasec/trivy:0.10.2
        with:
          args: --cache-dir /var/lib/trivy --no-progress --exit-code 0 --severity UNKNOWN,LOW,MEDIUM my-container:my-tag
      - name: Scan for HIGH, CRITICAL vulnerabilities
        uses: docker://docker.io/aquasec/trivy:0.10.2
        with:
          args: --cache-dir /var/lib/trivy --no-progress --exit-code 1 --severity HIGH,CRITICAL my-container:my-tag
  scan:
    name: Scan for vulnerabilities
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "List containers"
        id: list-containers
        run: |
          docker images
      - name: Scan for LOW, MED vulnerabilities
        uses: docker://docker.io/aquasec/trivy:0.10.2
        with:
          args: --cache-dir /var/lib/trivy --no-progress --exit-code 0 --severity UNKNOWN,LOW,MEDIUM my-container:my-tag
      - name: Scan for HIGH, CRITICAL vulnerabilities
        uses: docker://docker.io/aquasec/trivy:0.10.2
        with:
          args: --cache-dir /var/lib/trivy --no-progress --exit-code 1 --severity HIGH,CRITICAL my-container:my-tag
      
